# Generated by Django 3.1 on 2021-04-27 15:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workshop', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imginfo',
            name='time',
            field=models.DateField(blank=True, default=datetime.datetime(2021, 4, 27, 23, 44, 34, 275366), null=True),
        ),
    ]
