# Generated by Django 3.1 on 2021-04-28 05:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workshop', '0002_auto_20210427_2344'),
    ]

    operations = [
        migrations.RenameField(
            model_name='imginfo',
            old_name='file_name',
            new_name='value',
        ),
        migrations.RemoveField(
            model_name='imginfo',
            name='path',
        ),
        migrations.AlterField(
            model_name='imginfo',
            name='time',
            field=models.DateField(blank=True, default=datetime.datetime(2021, 4, 28, 13, 3, 37, 783564), null=True),
        ),
    ]
