# Generated by Django 3.1 on 2021-04-29 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workshop', '0004_auto_20210428_1307'),
    ]

    operations = [
        migrations.AddField(
            model_name='imginfo',
            name='name',
            field=models.CharField(default=1, max_length=16),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='imginfo',
            name='id',
            field=models.CharField(max_length=8),
        ),
        migrations.AlterField(
            model_name='imginfo',
            name='time',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='imginfo',
            name='value',
            field=models.CharField(max_length=64, primary_key=True, serialize=False),
        ),
    ]
