# Generated by Django 3.1 on 2021-04-29 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workshop', '0005_auto_20210429_1643'),
    ]

    operations = [
        migrations.RenameField(
            model_name='machineinfo',
            old_name='time',
            new_name='update_time',
        ),
        migrations.RemoveField(
            model_name='imginfo',
            name='time',
        ),
        migrations.AddField(
            model_name='imginfo',
            name='data',
            field=models.ImageField(default=1, upload_to=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='imginfo',
            name='update_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
