# Generated by Django 3.1 on 2021-05-12 16:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workshop', '0007_auto_20210429_2332'),
    ]

    operations = [
        migrations.RenameField(
            model_name='staticinfo',
            old_name='data',
            new_name='date',
        ),
    ]
